name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.4
  dio: ^5.5.0+1
  get: ^4.6.6
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
